### ISSUE TITLE
Consistency between production build and development server

### ISSUE THREAD

**Issue by HunteRoi** [Arsero/docusaurus-graph#1]
Hey there @Arsero !

This plugin is quite interesting! I find it very useful but I think there's a discrepancy between the production build (building the app then serving) and the development server (starting the app in development mode).

I find it very difficult that the plugin makes it two separate environments needing different setups when the goal is to pick up relationships between files and displaying those in a graph.

Would it be possible to find a way so that when executing `start` and `build`, it works the same way?

**Comment by HunteRoi** [comment]
https://github.com/Arsero/docusaurus-graph/blob/1d4008cb4e5b64c3401fd09f8942e2d534b150d7/src/index.ts#L30

Also it seems that you hardcoded the `build` folder but I am pretty sure we can overwrite that in docusaurus, which would ultimately break your package, right?

Source: https://docusaurus.io/docs/cli#docusaurus-build-sitedir

**Comment by Arsero** [comment]
Hi HunteRoi,

Thank you for reporting this issue! The problem has been resolved in the latest release, version 2.0.0. 🎉 Please update to this version and let me know if you encounter any further issues.

Feel free to reopen this issue or create a new one if needed. Thanks for your support!

Best regards,
Arsero
